a = []
b = input('Возраст пользователя: ')
g = input('Пол пользователя: ')
d = input('Имя пользователя: ')
y = input('Город пользователя: ')
h = input('Класс пользователя: ')
a.append(b)
a.append(g)
a.append(d)
a.append(y)
a.append(h)
print(a)