b = []
c = input("Возраст пользователя:  ")
d = input("Пол пользователя:  ")
e = input("Имя пользователя:  ")
f = input("Город пользователя:  ")
g = input("Класс пользователя:  ")
b.append(c)
b.append(d)
b.append(e)
b.append(f)
b.append(g)
print(b)